const scene=new THREE.Scene();scene.background=new THREE.Color(0xbfe7ff);scene.fog=new THREE.Fog(0xbfe7ff,80,220);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,500);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;document.querySelector('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x65815d,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(60,90,35);sun.castShadow=true;scene.add(sun);
const world=createWorld(scene),race=createSkySprint(scene),player=createPlayer(scene);player.position.set(0,.1,22);
const keys={};addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);
let yaw=.25,pitch=.48,drag=false,lx=0,ly=0;renderer.domElement.onmousedown=e=>{drag=true;lx=e.clientX;ly=e.clientY};addEventListener('mouseup',()=>drag=false);addEventListener('mousemove',e=>{if(!drag)return;yaw-=(e.clientX-lx)*.006;pitch=Math.max(.2,Math.min(1.05,pitch-(e.clientY-ly)*.004));lx=e.clientX;ly=e.clientY});
let skyCountdown=8,returnTimer=0,elapsed=0,secondGame=false,obstacleTime=0,obstacleScore=0;const clock=new THREE.Clock();
function setRaceVisible(v){document.querySelector('#raceHud').style.display=v?'block':'none';document.querySelector('#raceBoard').style.display=v?'block':'none'}
function startObstacleDash(){secondGame=true;obstacleTime=45;obstacleScore=0;player.position.set(0,.1,25);player.rotation.y=0;setRaceVisible(false);document.querySelector('#eventName').textContent='OBSTACLE DASH';document.querySelector('#venue').innerHTML='<b>ATHLETICS CENTRE</b><span>Dodge, jump and sprint to the finish</span>';showToast('SECOND EVENT: OBSTACLE DASH!');}
function updateObstacleDash(dt){if(!secondGame)return;obstacleTime-=dt;const speed=obstacleTime>0?1:0;const k=keys;const f=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),d=new THREE.Vector3();if(k.KeyW)d.add(f);if(k.KeyS)d.sub(f);if(k.KeyA)d.add(r);if(k.KeyD)d.sub(r);if(d.lengthSq()){d.normalize();player.position.addScaledVector(d,(k.ShiftLeft||k.ShiftRight?12:6)*dt);player.rotation.y=Math.atan2(d.x,d.z)}if(k.Space&&player.userData.ground){player.userData.vy=9;player.userData.ground=false}player.userData.vy-=22*dt;player.position.y+=player.userData.vy*dt;if(player.position.y<=.1){player.position.y=.1;player.userData.vy=0;player.userData.ground=true}player.position.x=Math.max(-26,Math.min(26,player.position.x));player.position.z=Math.max(-35,Math.min(90,player.position.z));if(player.position.z>85){obstacleScore=Math.max(obstacleScore,1000+Math.floor(obstacleTime*20));showToast('FINISH! SCORE '+obstacleScore);secondGame=false;setTimeout(startThirdPlaceholder,2500)}if(obstacleTime<=0&&secondGame){showToast('TIME! SCORE '+obstacleScore);secondGame=false;setTimeout(startThirdPlaceholder,1800)}}
function startThirdPlaceholder(){document.querySelector('#eventName').textContent='NEXT EVENT';document.querySelector('#venue').innerHTML='<b>CHALLENGE ARENA</b><span>Next mini-game loading...</span>';showToast('NEXT EVENT READY — CHALLENGE ARENA');}
function updateRaceHUD(){const h=document.querySelector('#raceHud'),b=document.querySelector('#raceBoard');if(!race.active&&!race.finished){h.style.display='block';b.style.display='none';document.querySelector('#raceState').textContent='Starting in '+Math.ceil(skyCountdown)+'s';document.querySelector('#raceTime').textContent='GET READY';document.querySelector('#raceCheckpoint').textContent='SKY COURSE · 8 CHECKPOINTS';document.querySelector('#raceStats').textContent='COINS 0 · BOOST READY';return}setRaceVisible(true);document.querySelector('#raceState').textContent=race.finished?'RESULTS':'RACE LIVE';document.querySelector('#raceTime').textContent=race.finished?race.time.toFixed(2)+'s':race.time.toFixed(2)+'s';document.querySelector('#raceCheckpoint').textContent='CHECKPOINT '+race.checkpoint+' / 8';document.querySelector('#raceStats').textContent='COINS '+(race.coins||0)+' · BOOST '+((race.boost||0)>0?race.boost.toFixed(1)+'s':'READY');if(race.finished){const board=skySprintLeaderboard(race);b.innerHTML='<b>LEADERBOARD</b>'+board.slice(0,6).map((x,i)=>'<div class="race-row '+(x.name==='YOU'?'you':'')+'"><span>'+(i+1)+'. '+x.name+'</span><span>'+(x.finished?x.time.toFixed(2)+'s':'--')+'</span></div>').join('')}}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;
  if(!secondGame&&!race.active&&!race.finished&&!race.playerFinished){skyCountdown-=dt;if(skyCountdown<=0){startSkySprint(player,race);showToast('GO! RUN TO THE FINISH!');setRaceVisible(true)}}
  if(secondGame)updateObstacleDash(dt);else if(race.active)updateSkySprint(player,keys,dt,yaw,race,showToast);else if(!race.finished&&!race.playerFinished)updatePlayer(player,keys,dt,yaw,showToast);
  if(race.playerFinished&&!race.finished){race.finished=true;returnTimer=0;const board=skySprintLeaderboard(race);const place=board.findIndex(x=>x.name==='YOU')+1;showToast(place===1?'1ST PLACE! 🏆':'FINISHED — PLACE '+place)}
  if(race.finished){returnTimer+=dt;if(returnTimer>6){race.finished=false;race.playerFinished=false;race.playerFinishTime=null;race.rivalFinishTimes=[];returnTimer=0;skyCountdown=12;player.position.set(0,.1,22);setRaceVisible(false);showToast('Back to Olympic Plaza')}}
  updateCamera(camera,player,yaw,race.active?.28:pitch);
  
  updateUI(player,dt);updateRaceHUD();renderer.render(scene,camera)
}
try{loop()}catch(err){console.error(err);const e=document.createElement('div');e.style='position:fixed;inset:20px;background:#200;color:#fff;padding:20px;z-index:99;font:16px monospace;white-space:pre-wrap';e.textContent='GAME ERROR\\n'+err.stack;document.body.appendChild(e)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});