import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const C={maxPlayers:8,respawnSeconds:5};
const R={Common:1,Uncommon:1.05,Rare:1.1,Epic:1.15,Legendary:1.2};
const W=[
{name:'Pulse Blaster',rarity:'Common',damage:18,rate:4,color:0x70e1ff},
{name:'Nova Scatter',rarity:'Uncommon',damage:10,rate:2.4,pellets:5,spread:.15,color:0x79ff9f},
{name:'Rail Lance',rarity:'Rare',damage:55,rate:1.1,color:0xffd86b},
{name:'Arc Cannon',rarity:'Epic',damage:32,rate:1.8,splash:3.5,color:0xd89bff},
{name:'Nova Rocket',rarity:'Legendary',damage:70,rate:.7,splash:6,color:0xff7b7b}];
const chars=[['Volt',0x43d9ff,'Speed Surge'],['Nova',0xff5f8f,'Energy Shield'],['Echo',0x8b7bff,'Decoy Drone'],['Flux',0x53f08a,'Gravity Pulse'],['Blaze',0xffa347,'Shockwave'],['Zero',0xdde8ff,'Phase Dash'],['Pixel',0xffe45c,'Repair Field'],['Orbit',0x72a7ff,'Jet Burst']].map(x=>({name:x[0],color:x[1],ability:x[2]}));
const s={score:0,deaths:0,weapon:0,bombs:3,ability:true,time:0,yaw:0,keys:new Set(),locked:false,jump:0,grounded:true,sliding:false,event:'CALM'};
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,220),renderer=new THREE.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.querySelector('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x9ed7ff,0x101528,2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(25,35,10);sun.castShadow=true;scene.add(sun);
const world=new THREE.Group();scene.add(world);const shots=[],bombs=[],fx=[],clock=new THREE.Clock();
const mat=(c,e=0,i=0)=>new THREE.MeshStandardMaterial({color:c,metalness:.35,roughness:.48,emissive:e,emissiveIntensity:i});
function box(x,y,z,w,h,d,c,e=0,i=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,e,i));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;world.add(m)}
function arena(){box(0,-.5,0,80,1,80,0x111d33);const g=new THREE.GridHelper(80,40,0x36bde8,0x18304d);g.position.y=.03;world.add(g);for(const p of [[0,3,-39],[0,3,39],[-39,3,0],[39,3,0]])box(p[0],p[1],p[2],p[0]===0?80:1,6,p[2]===0?80:1,0x172942,0x165d9a,.5);for(let i=0;i<18;i++){const x=(Math.random()-.5)*64,z=(Math.random()-.5)*64,h=3+Math.random()*8;box(x,h/2,z,3+Math.random()*4,h,3+Math.random()*4,0x1a2942,0x163e67,.45)}for(let i=0;i<5;i++){const p=new THREE.Mesh(new THREE.CylinderGeometry(2,2,.24,20),mat(0x26d9b4,0x26d9b4,2));p.position.set((i-2)*14,.12,i%2?12:-12);world.add(p)}}
function make(c){const g=new THREE.Group();g.userData={hp:100,alive:true,char:c};const b=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.1,6,12),mat(c.color,c.color,.18));b.position.y=1.15;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.48,20,16),mat(0xf1c7a7));h.position.y=2.15;g.add(h);return g}
arena();const player=make(chars[0]);player.position.set(0,0,28);scene.add(player);const bots=[];for(let i=1;i<C.maxPlayers;i++){const b=make(chars[i]),a=(i-1)*Math.PI*2/7;b.position.set(Math.cos(a)*27,0,Math.sin(a)*27);b.userData.ai={cool:Math.random()};scene.add(b);bots.push(b)}const all=()=>[player,...bots],damage=w=>Math.round(w.damage*R[w.rarity]);
function eliminate(t,k){t.userData.alive=false;t.visible=false;t.userData.respawnAt=s.time+C.respawnSeconds;if(k===player)s.score++;if(t===player)s.deaths++;hud()}
function respawn(t){t.userData.hp=100;t.userData.alive=true;t.visible=true;const a=Math.random()*Math.PI*2;t.position.set(Math.cos(a)*30,0,Math.sin(a)*30)}
function blast(pos,r,dmg,owner){const e=new THREE.Mesh(new THREE.SphereGeometry(.2,12,12),new THREE.MeshBasicMaterial({color:0xffb84d,transparent:true,opacity:.8}));e.position.copy(pos);scene.add(e);fx.push({m:e,t:.25});for(const t of all()){if(t===owner||!t.userData.alive)continue;const q=t.position.distanceTo(pos);if(q<r){t.userData.hp-=dmg*(1-q/r);if(t.userData.hp<=0)eliminate(t,owner)}}}
function fire(owner,o,d,w){const p=new THREE.Mesh(new THREE.SphereGeometry(.11,8,8),mat(w.color,w.color,3));p.position.copy(o);p.userData={dir:d.normalize(),owner,w,life:2.2};scene.add(p);shots.push(p)}
function shoot(){if(!player.userData.alive)return;const w=W[s.weapon],now=s.time;if(now<(player.userData.nextShot||0))return;player.userData.nextShot=now+1/w.rate;const o=player.position.clone().add(new THREE.Vector3(0,1.5,.8)),d=new THREE.Vector3(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),s.yaw);for(let i=0;i<(w.pellets||1);i++){const q=d.clone();q.x+=(Math.random()-.5)*(w.spread||0);fire(player,o,q,w)}}
function bomb(){if(!s.bombs||!player.userData.alive)return;s.bombs--;const b=new THREE.Mesh(new THREE.SphereGeometry(.3,12,12),mat(0xff6c6c,0xff2020,2));b.position.copy(player.position).add(new THREE.Vector3(0,1.3,0));b.userData={v:new THREE.Vector3(0,5,-13).applyAxisAngle(new THREE.Vector3(0,1,0),s.yaw),life:1.3};scene.add(b);bombs.push(b);hud()}
function ability(){if(!s.ability||!player.userData.alive)return;s.ability=false;player.userData.shield=s.time+2.5;player.scale.setScalar(1.15);setTimeout(()=>{player.scale.setScalar(1);s.ability=true;hud()},4500);hud()}
function move(dt){if(!player.userData.alive){if(s.time>=player.userData.respawnAt)respawn(player);return}if(s.keys.has('Space')&&s.grounded){s.jump=7.5;s.grounded=false}s.jump-=18*dt;player.position.y+=s.jump*dt;if(player.position.y<=0){player.position.y=0;s.jump=0;s.grounded=true}s.sliding=s.keys.has('KeyC');const f=(s.keys.has('KeyW')?1:0)-(s.keys.has('KeyS')?1:0),x=(s.keys.has('KeyD')?1:0)-(s.keys.has('KeyA')?1:0),v=new THREE.Vector3(x,0,-f).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),s.yaw),speed=s.sliding?16:(s.keys.has('ShiftLeft')||s.keys.has('ShiftRight')?13:8);if(v.lengthSq())player.position.addScaledVector(v,speed*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-36,36);player.position.z=THREE.MathUtils.clamp(player.position.z,-36,36)}
function botsUpdate(dt){for(const b of bots){if(!b.userData.alive){if(s.time>=b.userData.respawnAt)respawn(b);continue}const v=player.position.clone().sub(b.position),d=v.length();v.y=0;if(d>9)b.position.addScaledVector(v.normalize(),dt*5);b.lookAt(player.position.x,b.position.y+1,player.position.z);b.userData.ai.cool-=dt;if(d<30&&b.userData.ai.cool<=0){b.userData.ai.cool=1.3+Math.random()*1.2;fire(b,b.position.clone().add(new THREE.Vector3(0,1.4,0)),player.position.clone().sub(b.position),W[(bots.indexOf(b)+1)%W.length])}}}
function projectilesUpdate(dt){for(let i=shots.length-1;i>=0;i--){const p=shots[i];p.position.addScaledVector(p.userData.dir,22*dt);p.userData.life-=dt;let hit;for(const t of all())if(t!==p.userData.owner&&t.userData.alive&&p.position.distanceTo(t.position)<1.1){hit=t;break}if(hit){const w=p.userData.w;if(w.splash)blast(p.position,w.splash,damage(w),p.userData.owner);else if(hit.userData.shield<=s.time) {hit.userData.hp-=damage(w);if(hit.userData.hp<=0)eliminate(hit,p.userData.owner)}scene.remove(p);shots.splice(i,1);continue}if(p.userData.life<=0){scene.remove(p);shots.splice(i,1)}}}
function bombsUpdate(dt){for(let i=bombs.length-1;i>=0;i--){const b=bombs[i];b.userData.v.y-=10*dt;b.position.addScaledVector(b.userData.v,dt);b.userData.life-=dt;if(b.position.y<.3)b.userData.v.y*=-.45;if(b.userData.life<=0){blast(b.position,6,45,player);scene.remove(b);bombs.splice(i,1)}}}
function worldUpdate(){const weather=['clear','ion storm','neon rain'][Math.floor(s.time/45)%3];s.event=weather==='clear'?'CALM':'ARENA '+weather.toUpperCase();scene.background=new THREE.Color().setHSL(.6,.65,.16+.08*(Math.sin(s.time/20)+1))}
function cameraUpdate(){const t=player.position.clone().add(new THREE.Vector3(0,1.5,0)),d=s.locked?5.4:7.2,o=new THREE.Vector3(Math.sin(s.yaw)*d,3.2,Math.cos(s.yaw)*d);camera.position.lerp(t.clone().add(o),.12);camera.lookAt(t)}
function hud(){const w=W[s.weapon];document.querySelector('#score').textContent=s.score;document.querySelector('#deaths').textContent=s.deaths;document.querySelector('#weapon').textContent=w.name+' · '+w.rarity;document.querySelector('#damage').textContent='DMG '+damage(w);document.querySelector('#bombs').textContent='BOMBS '+s.bombs;document.querySelector('#ability').textContent=s.ability?'ABILITY READY':'ABILITY CHARGING';document.querySelector('#event').textContent=s.event}
addEventListener('keydown',e=>{s.keys.add(e.code);if(e.code==='Space')e.preventDefault();if(e.code==='KeyQ')ability();if(e.code==='KeyE')bomb();if(/^Digit[1-5]$/.test(e.code))s.weapon=+e.code.slice(-1)-1;hud()});addEventListener('keyup',e=>s.keys.delete(e.code));renderer.domElement.onclick=()=>renderer.domElement.requestPointerLock?.();document.addEventListener('pointerlockchange',()=>s.locked=document.pointerLockElement===renderer.domElement);document.addEventListener('mousemove',e=>{if(s.locked)s.yaw-=e.movementX*.0024});addEventListener('mousedown',e=>{if(e.button===0)shoot();if(e.button===2)bomb()});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);s.time+=dt;move(dt);botsUpdate(dt);projectilesUpdate(dt);bombsUpdate(dt);worldUpdate();cameraUpdate();hud();renderer.render(scene,camera)}const menu=document.querySelector('#menu'),select=document.querySelector('#select'),lobby=document.querySelector('#lobby'),game=document.querySelector('#game'),gameHud=document.querySelector('#gameHud');
const charGrid=document.querySelector('#characters'),slots=document.querySelector('#slots');let selectedChar=0;
chars.forEach((c,i)=>{const b=document.createElement('button');b.className='character'+(i===0?' selected':'');b.innerHTML='<div class="orb" style="background:#'+c.color.toString(16).padStart(6,'0')+';color:#'+c.color.toString(16).padStart(6,'0')+'"></div><strong>'+c.name+'</strong><span>'+c.ability+'</span>';b.onclick=()=>{selectedChar=i;document.querySelectorAll('.character').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};charGrid.appendChild(b)});
function show(el){[menu,select,lobby].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')}
document.querySelector('#playBtn').onclick=()=>show(select);
document.querySelector('#createBtn').onclick=()=>show(lobby);
document.querySelector('#joinBtn').onclick=()=>{const code=prompt('Enter room code');if(code)show(lobby)};
document.querySelector('#loadoutBtn').onclick=()=>show(select);
document.querySelector('#continueBtn').onclick=()=>show(lobby);
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(menu));
chars.forEach((c,i)=>{const d=document.createElement('div');d.className='slot'+(i<3?' ready':'');d.innerHTML='<div class="dot">'+(i+1)+'</div><div><small>'+ (i===0?'YOU':'BOT') +'</small><strong>'+c.name+'</strong></div>';slots.appendChild(d)});
document.querySelector('#copyRoom').onclick=async()=>{try{await navigator.clipboard.writeText('NOVA-7X4')}catch{}};
document.querySelector('#launchBtn').onclick=()=>{[menu,select,lobby].forEach(x=>x.classList.add('hidden'));game.classList.remove('hidden');gameHud.classList.remove('hidden');const c=chars[selectedChar];player.userData.char=c;player.children[0].material.color.setHex(c.color);document.querySelector('#playerName').textContent=c.name;document.querySelector('#playerAbility').textContent=c.ability;hud()};
hud();loop();